Repository rropen/absense-planner, pull requests merged in 2025-06, with the labels that each got.

#536 AP - Implement api tokens
  ap_src/ap_app/static/js/teams.js
  ap_src/ap_app/utils/switch_permissions.py
  ap_src/ap_app/utils/teams_utils.py
  ap_src/ap_app/views/calendarview.py
  ap_src/ap_app/views/teams.py
  ap_src/ap_app/views/views.py
  ap_src/templates/teams/create_team.html
  ap_src/templates/teams/edit_team.html
  example_env.txt
Labels: backend, debt, risk

#539 AP - Add profiling features + huge optimisations
  ap_src/ap_app/middleware.py
  ap_src/ap_app/migrations/0001_initial.py
  ap_src/ap_app/urls.py
  ap_src/ap_app/utils/switch_permissions.py
  ap_src/ap_app/utils/teams_utils.py
  ap_src/ap_app/views/calendarview.py
  ap_src/ap_app/views/teams.py
  ap_src/ap_site/settings.py
  example_env.txt
  requirements.txt
  testing_requirements.txt
Labels: backend, debt, defect, frontend

#542 Fix team title missing
  ap_src/ap_app/views/calendarview.py
  ap_src/templates/calendars/elements/calendar_element.html
  ap_src/templates/calendars/specific_team_calendar.html
  ap_src/templates/teams/dashboard.html
  ap_src/templates/teams/join_team.html
Labels: defect, frontend

#567 Handle api errors
  ap_src/ap_app/static/js/delete_element.js
  ap_src/ap_app/utils/errors.py
  ap_src/ap_app/utils/teams_utils.py
  ap_src/ap_app/views/calendarview.py
  ap_src/ap_app/views/teams.py
  ap_src/ap_site/settings.py
  ap_src/templates/base.html
  ap_src/templates/teams/edit_team.html
  example_env.txt
Labels: backend, debt, frontend, risk, feature: teams structure

#578 Store user details on TA
  ap_src/ap_app/urls.py
  ap_src/ap_app/utils/teams_utils.py
  ap_src/ap_app/views/absences.py
  ap_src/ap_app/views/views.py
  ap_src/templates/ap_app/settings.html
  ap_src/templates/calendars/elements/calendar_element.html
Labels: backend, debt, defect, feature, frontend

#587 AP: Standardise setup script name
  setup.bat
  setup.sh
Labels: debt

#632 AP: Format Codebase with Prettier and add it as a GitHub action
  .github/workflows/main.yml
  .github/workflows/prettier.yml
  .github/workflows/ruff.yml
  .prettierignore
  .vscode/launch.json
  DEVELOPER.md
  ap_src/ap_app/fixtures/colours.json
  ap_src/ap_app/fixtures/roles.json
  ap_src/ap_app/fixtures/statuses.json
  ap_src/ap_app/fixtures/teams.json
  ap_src/ap_app/fixtures/users.json
  ap_src/ap_app/static/css/bulma.min.css
  ap_src/ap_app/static/css/dark.css
  ap_src/ap_app/static/css/error_pages.css
  ap_src/ap_app/static/css/layout.css
  ap_src/ap_app/static/css/light.css
  ap_src/ap_app/static/js/absence_creation.js
  ap_src/ap_app/static/js/api_calendar.js
  ap_src/ap_app/static/js/button_spinner.js
  ap_src/ap_app/static/js/core.js
  ap_src/ap_app/static/js/darkMode.js
  ap_src/ap_app/static/js/delete_element.js
  ap_src/ap_app/static/js/login.js
  ap_src/ap_app/static/js/profile_update.js
  ap_src/ap_app/static/js/script.js
  ap_src/ap_app/static/js/teams.js
  package-lock.json
  yarn.lock
Labels: debt

#633 AP: Update Dockerfile
  Dockerfile
Labels: debt

#636 Add pre-commit hooks
  .pre-commit-config.yaml
  CONTRIBUTING.md
  DEVELOPER.md
  README.md
  pyproject.toml
  setup.bat
  setup.sh
  uv.lock
Labels: debt

#641 fix(setup): remove erroneous teams fixture
  ap_src/ap_app/fixtures/teams.json
Labels: debt, defect

#639 AP: Add password visibility toggle in sign up page
  ap_src/ap_app/forms.py
  ap_src/ap_app/static/js/login.js
  ap_src/templates/registration/login.html
  ap_src/templates/registration/signup.html
Labels: feature, frontend
